url: "https://daysgonegames.github.io"
baseurl: ""

# Site settings
title: DaysGone Games
email: contact@daysgonegames.com
description: "DaysGone Games - Independent Game Studio"

# Team
people:
- name: Usagi Knight
  pic: 1
  position: Designer

# Social networks
social:
  - title: twitter
    url: https://x.com/DaysGoneGames
  - title: comment
    url: https://discord.com/channels/1480492767347081236/1480492768403918870

# Build settings
markdown: kramdown
permalink: pretty
